"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------- .env loaded -----------------
# Database
DATABASE_URL = os.getenv("DATABASE_URL")

# Application
DEBUG = os.getenv("DEBUG", "False") == "True"
RATELIMIT_ENABLED_ENV = os.getenv("RATELIMIT_ENABLED", "True") == "True"
SECRET_KEY = os.getenv("SECRET_KEY")

# Redis
REDIS_URL = os.getenv("REDIS_URL")
REDIS_CACHE_URL = os.getenv("REDIS_CACHE_URL")

# External APIs
TWELVE_DATA_API_KEY = os.getenv("TWELVE_DATA_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# CORS
ALLOWED_ORIGINS = os.getenv("ALLOWED_ORIGINS", "http://localhost:5173")
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    # Local apps
    "accounts",
    "watchlist",
    "stocks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {"default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)}

AUTH_USER_MODEL = "accounts.User"

# Rate limiting
RATELIMIT_ENABLED = RATELIMIT_ENABLED_ENV
RATELIMIT_USE_CACHE = "default"
RATELIMIT_VIEW = "config.limiter.ratelimit_exceeded_handler"


# Redis cache (used by django-ratelimit)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}


# ----------------- Constants / hard coded -----------------
MAX_WATCHLIST_ITEMS = 12


# Redis Caching invalidation TTL.
CACHE_TTL_DEFAULT = 60 * 60  # 1 hour

CACHE_TTL_AUTH = 60 * 60 * 24 * 30  # 30 days — cache reset on password, status, role, or profile changes.

CACHE_TTL_STOCK_PRICE = 90  # 1 minute, 30 seconds — free-tier API, avoid re-fetching too often

INSIGHT_STALE_DAYS = 15  # long_term_relevance & risks regenerate after this many days; company_overview never changes

INSIGHT_REFRESH_INTERVAL = 60 * 60 * 24  # check once daily for stale insights

# External Apis
TWELVE_DATA_BASE_URL = "https://api.twelvedata.com"
GROQ_MODEL = "llama-3.3-70b-versatile"

# Celery
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True


# LOGGER CONFIG
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "()": "colorlog.ColoredFormatter",
            "format": "%(log_color)s%(levelname)s:%(reset)s     %(name)s - %(message)s",
            "log_colors": {
                "DEBUG": "cyan",
                "INFO": "green",
                "WARNING": "yellow",
                "ERROR": "red",
                "CRITICAL": "bold_red",
            },
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Startup logging (runs once on server boot, skips autoreloader's parent process)
import os

if os.environ.get("RUN_MAIN") == "true":
    from config.logging import log_startup

    log_startup()


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# CORS
CORS_ALLOWED_ORIGINS = ALLOWED_ORIGINS.split(",")

STATIC_URL = "static/"

# Django REST Framework
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "config.limiter.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}
