# Generated by Django 6.0.7 on 2026-08-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateField()),
            ],
            options={
                'unique_together': {('stock_symbol', 'recorded_at')},
            },
        ),
    ]
